site_name: Lighter
theme:
  icon:
    repo: fontawesome/brands/github
  font:
    code: Roboto Mono
  name: 'material'
  favicon: 'assets/images/lighter_favicon.png'
  logo: 'assets/images/lighter_logo.png'
  features:
    - content.code.copy
    - content.code.select
    - header.autohide
    - content.tooltips
    - attr_list
    - footnotes
    - navigation.tabs

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra_css:
  - assets/extra.css

plugins:
  - search
  - autorefs
  - mkdocstrings

nav:
  - 'index.md'
  - 'Basics': 
    - '5 Minute Example': 'basics/5-minute-example.md'
    - 'Config': 'basics/config.md'
    - 'System': 'basics/system.md'
    - 'Trainer': 'basics/trainer.md'
    - 'Project-specific code': 'basics/project-specific-code.md'
  - 'Advanced':
    - 'Postprocessing': 'advanced/postprocessing.md'
    - 'Inferer': 'advanced/inferer.md'
    - 'Callbacks': 'advanced/callbacks.md'
  - 'API': api.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


repo_name: project-lighter/lighter
repo_url: https://github.com/project-lighter/lighter
