name: Auto Publish

on:
  workflow_run:
    workflows: ["Lighter CI"]  # Mustes the CI workflow name
    types: [completed]

jobs:
  autopublish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage badge artifact
        uses: actions/download-artifact@v2
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-badge

      - name: Check out code
        uses: actions/checkout@v2
        with:
          # Usually, you want to check out the same commit tested by the CI
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install uv
        run: make setup

      - name: Bump version & commit badge
        run: |
          # 1) Bump version
          make bump-prerelease

          # 2) Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 3) Stage any changes (the version bump & coverage.svg)
          git add .

          # 4) Commit in one go
          git commit -m "Bump version" || echo "No version bump or coverage changes to commit"

          # 5) Push changes
          git push

      - name: Build distribution
        run: uv build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
